# Install basic python dependencies
language: python

# These are required for python3.7
sudo: required
dist: xenial
python: "3.7"

# Don't test branches created by sharelatex/overleaf
branches:
  except:
    - /^sharelatex-.*$/

# Install project dependencies
install:
  - pip install -r requirements.txt

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
  # Execute the pytest test suite with verbosity
  - pytest . -vv
